### ISSUE TITLE
Error: undefined method 'connect' for TCPSocket.class

### ISSUE THREAD

**Issue by yunixon** [636f7374/durian.cr#3]
In lib/durian/src/durian/extra/http/client.cr:26:15

 26 | TCPSocket.connect hostname, @port, resolver, @connect_timeout
                ^------
Error: undefined method 'connect' for TCPSocket.class

```
crystal: 0.35.1

durian:
    git: https://github.com/636f7374/durian.cr.git
    version: 0.1.4
```
